### ISSUE TITLE
publish a new release containing the latest changes on master (e.g. browser support)

### ISSUE THREAD

**Issue by GlenDC** [testground/sdk-js#28]
Such that testground (and its users) can make use of an actual release for browser-enabled testplans.

**Comment by laurentsenta** [comment]
Released 0.1.3
Quick checklist in case we have to do this again:

- [ ] `npm login` with an account that can release to `@testground/sdk-js`
- [ ] generate a token in github to create releases there
- [ ] `nvm use v16 && npm install && npm run release`

Hopefully, we'll switch to unified CI (https://github.com/protocol/.github) before the next release;
plus I'm unsure how aegir chooses between minor / major versions bumps.
